<?php

namespace fsm\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function getUserPhotoP($user) {
        $query = $this->createQueryBuilder('o')
                ->where('o.id = :user')
                ->leftjoin('o.photos', 'p')
                ->setParameter('user', $user)
                ->addSelect('p')
        ;
        return $query->getQuery()->getResult();
    }

    public function getlistUserPhoto() {
        $query = $this->createQueryBuilder('o')
                        ->leftjoin('o.photos', 'p')
                ->addSelect('p')
        ;
        return $query->getQuery()->getResult();
    }
    
    
    

}
