<?php

namespace fsm\EchangeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    
    public function getPhotoMainByUser($user) {
        $query = $this->createQueryBuilder('p')
                ->where('p.user = :user','p.principal= 1')
                ->join('p.user','u')
                ->setParameter('user',$user)
                ->addSelect('p','u')
                ;
        return $query->getQuery()->getResult();
    }
 public function getPhotoByUser($user) {
     $query = $this->createQueryBuilder('p')
                ->where('p.user = :user')
                ->join('p.user','u')
                ->setParameter('user',$user)
                ->addSelect('p','u')
                ;
        return $query->getQuery()->getResult();
     
 }
    
}
