parameters:
    database_driver: pdo_mysql
    node:
    node_paths:
    database_host: mysql51-108.perso
    database_port: null
    database_name: gitelugomanufa
    database_user: gitelugomanufa
    database_password: bprop789    
    mailer_auth_mode:  login
    mailer_transport:  smtp
    mailer_port: 587
    mailer_host: smtp.gite-lugos.fr
    mailer_user: postmaster@gite-lugos.fr
    mailer_password: bprop789
    locale: fr
    secret: ThisTokenIsNotSoSecretChangeIt44
    debug_toolbar: true
    debug_redirects: false
    use_assetic_controller: true
