<?php

namespace Proxies\__CG__\fsm\EchangeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Objet extends \fsm\EchangeBundle\Entity\Objet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'photos', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'id', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'nom', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'description', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'sens', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'prix', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'user', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'categories');
        }

        return array('__isInitialized__', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'photos', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'id', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'nom', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'description', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'sens', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'prix', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'user', '' . "\0" . 'fsm\\EchangeBundle\\Entity\\Objet' . "\0" . 'categories');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Objet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function RetourType($i)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'RetourType', array($i));

        return parent::RetourType($i);
    }

    /**
     * {@inheritDoc}
     */
    public function getSens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSens', array());

        return parent::getSens();
    }

    /**
     * {@inheritDoc}
     */
    public function setSens($sens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSens', array($sens));

        return parent::setSens($sens);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', array($prix));

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', array());

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\fsm\UserBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function addCategory(\fsm\EchangeBundle\Entity\Categorie $categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategory', array($categories));

        return parent::addCategory($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategory(\fsm\EchangeBundle\Entity\Categorie $categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategory', array($categories));

        return parent::removeCategory($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', array());

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function addPhoto(\fsm\EchangeBundle\Entity\Photo $photos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPhoto', array($photos));

        return parent::addPhoto($photos);
    }

    /**
     * {@inheritDoc}
     */
    public function removePhoto(\fsm\EchangeBundle\Entity\Photo $photos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePhoto', array($photos));

        return parent::removePhoto($photos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotos', array());

        return parent::getPhotos();
    }

}
