parameters:
#    fsm_echange.example.class: fsm\EchangeBundle\Example

services:
    fsm_Echange.habilitation:
        class : fsm\EchangeBundle\Services\habilitation
        arguments : [ @security.context]

